.TH "G:/Doxygen/class.h" 3 "Mon Oct 8 2018" "Doxygen_test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/Doxygen/class.h
.SH SYNOPSIS
.br
.PP
\fC#include 'iostream'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMy_Fish\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCNT_MAX\fP   10"
.br
.RI "The maxium number of print\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is a test to see how the doxygen generate the html\&.
.PP
\fBAuthor:\fP
.RS 4
Kevin 
.RE
.PP
\fBVersion:\fP
.RS 4
V1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
2018-10-8 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen_test from the source code\&.
