.TH "My_Fish" 3 "Mon Oct 8 2018" "Doxygen_test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
My_Fish
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMy_Fish\fP (int temp1, int temp2)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen_test from the source code\&.
